load 'zad2.rb'
task :default do
   ruby "zad2_test.rb"
   puts "Main script"
   ruby "zad2.rb"


end
task :test do
    ruby "zad2_test.rb"
end


task :yard do
 require 'yard'
 YARD::Rake::YardocTask.new do |t|
    t.stats_options = %w(--list-undoc)   
  end
end

task :doc %w(yard)


